---
- name: Make workspace directory structure
  file:
    state: directory
    path: "{{ workspace }}/{{ item }}"
    recurse: yes
  loop:
    - bin/
    - assets/
    - "{{ openshift.name }}/"

- name: Get openshift clients
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift.install_version }}/openshift-client-linux-{{ openshift.install_version }}.tar.gz", dest: "/tmp/oc.tar.gz" }
    - { url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift.install_version }}/openshift-install-linux-{{ openshift.install_version }}.tar.gz", dest: "/tmp/openshift-install.tar.gz" }

- name: Extract Openshift client
  unarchive:
    src: "/tmp/oc.tar.gz"
    dest: "{{ workspace }}/bin/"
    remote_src: yes
    include:
      - oc

- name: Extract Openshift installer
  unarchive:
    src: "/tmp/openshift-install.tar.gz"
    dest: "{{ workspace }}/bin/"
    remote_src: yes
    include:
      - openshift-install

- name: Get coreos info
  command: "{{ workspace }}/bin/openshift-install coreos print-stream-json"
  register: coreos

- set_fact:
     print_stream: "{{ coreos.stdout | from_json }}"

- debug: msg="{{ print_stream.architectures.x86_64.artifacts.metal.formats.iso.disk.location }}"

- name: Download ISO
  get_url:
    url: "{{ print_stream.architectures.x86_64.artifacts.metal.formats.iso.disk.location }}"
    dest: "{{ workspace }}/assets/rhcos-live.iso"
    checksum: "sha256:{{ print_stream.architectures.x86_64.artifacts.metal.formats.iso.disk.sha256 }}"
